server:
  port: 8081

spring:
  application:
    name: NexignTaskService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      isolation-level: read_committed
    listener:
      concurrency: 3
      missing-topics-fatal: false
      auto-startup: true
      ack-mode: record
  datasource:
    url: jdbc:postgresql://localhost:5432/nexign
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: DEBUG

task-executor:
  core-pool-size: 20 # Базовое количество потоков
  max-pool-size: 50 # Максимальное количество потоков
  queue-capacity: 100 # Размер очереди задач